declare const styles: {
  readonly area: string;
  readonly bubble: string;
  readonly chart: string;
  readonly cursor: string;
  readonly cut: string;
  readonly end: string;
  readonly frame: string;
  readonly grip: string;
  readonly kept: string;
  readonly mark: string;
  readonly outline: string;
  readonly overview: string;
  readonly playhead: string;
  readonly point: string;
  readonly reset: string;
  readonly start: string;
  readonly svg: string;
  readonly visible: string;
  readonly window: string;
  readonly zoomed: string;
};
export = styles;
