declare const styles: {
  readonly errorMessage: string;
  readonly finePrint: string;
  readonly formNote: string;
  readonly formProblem: string;
  readonly headline: string;
  readonly homeBody: string;
  readonly homeContent: string;
  readonly loginBody: string;
  readonly loginLede: string;
  readonly modal: string;
  readonly pitchNote: string;
  readonly quietAction: string;
  readonly reasons: string;
  readonly siwaButton: string;
  readonly state: string;
  readonly stateDetail: string;
  readonly stateError: string;
  readonly stateLabel: string;
  readonly stateReadonly: string;
};
export = styles;
